[build-system]
# PEP 508 specifications.
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.black]
line_length = 79

[tool.setuptools_scm]

[tool.coverage]
[tool.coverage.run]
include = ['citam/*']
omit = []
